# **MNIST Dataset Classification Using Dimensionality Reduction Methods**

## Load the MNIST dataset and split it into a training set and a test set (take the first 60,000 instances for training, and the remaining 10,000 for testing).

In [ ]:
# YOUR CODE HERE

# Global function
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE, LocallyLinearEmbedding, MDS

In [ ]:
# Load the data
df = pd.read_csv("/content/mnist_dataset.csv", index_col=0)
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          2    0    0    0    0    0    0    0    0    0  ...      0      0   
1          5    0    0    0    0    0    0    0    0    0  ...      0      0   
2          8    0    0    0    0    0    0    0    0    0  ...      0      0   
3          0    0    0    0    0    0    0    0    0    0  ...      0      0   
4          4    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
69995      1    0    0    0    0    0    0    0    0    0  ...      0      0   
69996      7    0    0    0    0    0    0    0    0    0  ...      0      0   
69997      4    0    0    0    0    0    0    0    0    0  ...      0      0   
69998      8    0    0    0    0    0    0    0    0    0  ...      0      0   
69999      7    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
69995      0      0      0      0      0      0      0      0  
69996      0      0      0      0      0      0      0      0  
69997      0      0      0      0      0      0      0      0  
69998      0      0      0      0      0      0      0      0  
69999      0      0      0      0      0      0      0      0  

[70000 rows x 785 columns]

In [ ]:
# Identify the target and the features
TARGET="label"
columns_predictors = [col for col in df.columns if col not in [TARGET]]

print(TARGET)
print(columns_predictors)

label
['1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9', '1x10', '1x11', '1x12', '1x13', '1x14', '1x15', '1x16', '1x17', '1x18', '1x19', '1x20', '1x21', '1x22', '1x23', '1x24', '1x25', '1x26', '1x27', '1x28', '2x1', '2x2', '2x3', '2x4', '2x5', '2x6', '2x7', '2x8', '2x9', '2x10', '2x11', '2x12', '2x13', '2x14', '2x15', '2x16', '2x17', '2x18', '2x19', '2x20', '2x21', '2x22', '2x23', '2x24', '2x25', '2x26', '2x27', '2x28', '3x1', '3x2', '3x3', '3x4', '3x5', '3x6', '3x7', '3x8', '3x9', '3x10', '3x11', '3x12', '3x13', '3x14', '3x15', '3x16', '3x17', '3x18', '3x19', '3x20', '3x21', '3x22', '3x23', '3x24', '3x25', '3x26', '3x27', '3x28', '4x1', '4x2', '4x3', '4x4', '4x5', '4x6', '4x7', '4x8', '4x9', '4x10', '4x11', '4x12', '4x13', '4x14', '4x15', '4x16', '4x17', '4x18', '4x19', '4x20', '4x21', '4x22', '4x23', '4x24', '4x25', '4x26', '4x27', '4x28', '5x1', '5x2', '5x3', '5x4', '5x5', '5x6', '5x7', '5x8', '5x9', '5x10', '5x11', '5x12', '5x13', '5x14', '5x15', '5x16', '5x17', '5x18'

In [ ]:
# Split data into a training set (60,000) and a test set (10,000)
df_train = df[:60000]
df_test = df[60000:]

print(df_train.shape, df_test.shape)

(60000, 785) (10000, 785)


In [ ]:
# Define the X_train, y_train, X_test, and y_test
X_train = df_train[columns_predictors]
y_train = df_train[TARGET]
X_test = df_test[columns_predictors]
y_test = df_test[TARGET]

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(60000, 784) (60000,) (10000, 784) (10000,)


In [ ]:
# Scale the X training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
display(X_train_scaled.shape)
print(X_train_scaled)

# Scale the X testing data
X_test_scaled = scaler.fit_transform(X_test)
display(X_test_scaled.shape)
print(X_test_scaled)

(60000, 784)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(10000, 784)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Train a Random Forest classifier on the dataset and time how long it takes, then evaluate the resulting model on the test set.

In [ ]:
%%time
# YOUR CODE HERE

# Train a Random Forest classifier
rfc_1 = RandomForestClassifier(n_estimators=50, random_state=42)
rfc_1.fit(X_train_scaled, y_train)

CPU times: user 27.5 s, sys: 98.4 ms, total: 27.6 s
Wall time: 33.4 s


RandomForestClassifier(n_estimators=50, random_state=42)

In [ ]:
# Evaluate the resulting model on the test
y_pred = rfc_1.predict(X_test_scaled)

# Performance evaluation
print("Performance Evaluation:\n")
print("Accuracy Score:\n", accuracy_score(y_test, y_pred), "\n")
print("Precision:\n", precision_score(y_test, y_pred, average='macro'), "\n")
print("Recall:\n", recall_score(y_test, y_pred, average='macro'), "\n")
print("F1 Score:\n", f1_score(y_test, y_pred, average='macro'), "\n")
print("Roc Auc Score:\n", roc_auc_score(y_test, rfc_1.predict_proba(X_test_scaled), multi_class='ovr'), "\n")

Performance Evaluation:

Accuracy Score:
 0.9472 

Precision:
 0.9472018866531933 

Recall:
 0.9480208778106128 

F1 Score:
 0.9471299468994397 

Roc Auc Score:
 0.9967449527966451 



## Use PCA to reduce the dataset’s dimensionality, with an explained variance ratio of 95%. Train a new Random Forest classifier on the reduced dataset and see how long it takes. Was training much faster? Next evaluate the classifier on the test set: how does it compare to the previous classifier?

In [ ]:
# YOUR CODE HERE
%%time
# Use PCA to reduce the dataset’s dimensionality
pca = PCA(n_components=0.95)
X_train_reduced = pca.fit_transform(X_train_scaled)
X_train_reduced.shape

CPU times: user 21.4 s, sys: 1.13 s, total: 22.5 s
Wall time: 13.2 s


(60000, 330)

In [ ]:
%%time
# Train a New Random Forest classifier using the reduced X_train
rfc_2 = RandomForestClassifier(n_estimators=50, random_state=42)
rfc_2.fit(X_train_reduced, y_train)

CPU times: user 1min 43s, sys: 79.6 ms, total: 1min 43s
Wall time: 1min 45s


RandomForestClassifier(n_estimators=50, random_state=42)

In [ ]:
%%time
# Evaluate the classifier on the test set
X_test_reduced = pca.transform(X_test_scaled)
y_pred = rfc_2.predict(X_test_reduced)

CPU times: user 603 ms, sys: 135 ms, total: 739 ms
Wall time: 475 ms


In [ ]:
# Performance evaluation
print("Performance Evaluation:\n")
print("Accuracy Score:\n", accuracy_score(y_test, y_pred), "\n")
print("Precision:\n", precision_score(y_test, y_pred, average='macro'), "\n")
print("Recall:\n", recall_score(y_test, y_pred, average='macro'), "\n")
print("F1 Score:\n", f1_score(y_test, y_pred, average='macro'), "\n")
print("Roc Auc Score:\n", roc_auc_score(y_test, rfc_2.predict_proba(X_test_reduced), multi_class='ovr'), "\n")

Performance Evaluation:

Accuracy Score:
 0.9301 

Precision:
 0.9295567869389185 

Recall:
 0.9292653008697792 

F1 Score:
 0.9292612450815941 

Roc Auc Score:
 0.9950259742372474 



**Comparison:**

Applying PCA actually slowed down the training process, extending it by more than 1 minute compared to training without PCA.

The performance deteriorated after using PCA, likely due to the loss of important dimensions that were critical for the classifier's accuracy.

## Use t-SNE to reduce the MNIST dataset, show result graphically.

In [ ]:
# YOUR CODE HERE

# Ploting the graphs takes too much time, so we subsample the data to only 5000 data
n_samples = 5000
indices = np.random.permutation(60000)[:n_samples]
X_subsampled_data = X_train_scaled[indices]
y_subsampled_data = y_train[indices]

In [ ]:
%%time
# Use t-SNE to reduce the MNIST dataset, show result graphically
reducer = TSNE(n_components=2, n_jobs=-1)
X_reduced = reducer.fit_transform(X_subsampled_data)
display(X_reduced.shape)
display(X_reduced)
fig = px.scatter(x=X_reduced[:,0], y=X_reduced[:,1], color=y_subsampled_data, title="TSNE")
fig.update_layout(coloraxis_colorbar=dict(title=TARGET), height=1000)
fig.update_yaxes(scaleanchor = "x", scaleratio = 1)
fig.show()

(5000, 2)

array([[ 6.7933876e+01,  3.0428303e+01],
       [-1.6376497e+00,  3.0052546e+01],
       [-4.4562263e+01,  1.3185583e+01],
       ...,
       [ 7.4467654e+00, -4.4951615e+00],
       [-8.3387461e+00,  1.8584507e-02],
       [ 2.7799700e+01,  3.4109402e+01]], dtype=float32)

CPU times: user 1min 33s, sys: 314 ms, total: 1min 33s
Wall time: 55.2 s


## Compare with other dimensionality methods: _Locally Linear Embedding_ (LLE) or _Multidimensional scaling_ (MDS).

In [ ]:
%%time
# YOR CODE HERE

#  Use LLE to reduce the MNIST dataset, show result graphically
reducer = LocallyLinearEmbedding(n_components=2, n_jobs=-1)
X_reduced = reducer.fit_transform(X_subsampled_data)
display(X_reduced.shape)
display(X_reduced)
fig = px.scatter(x=X_reduced[:,0], y=X_reduced[:,1], color=y_subsampled_data, title="LLE")
fig.update_layout(coloraxis_colorbar=dict(title=TARGET), height=1000)
fig.update_yaxes(scaleanchor = "x", scaleratio = 1)
fig.show()

(5000, 2)

array([[ 0.0342106 , -0.01480456],
       [-0.0025605 ,  0.00579412],
       [-0.00953333, -0.00576699],
       ...,
       [-0.00577427,  0.00182146],
       [-0.00548572,  0.00163832],
       [ 0.00203091,  0.00601275]])

CPU times: user 6.16 s, sys: 1.96 s, total: 8.12 s
Wall time: 4.5 s


In [ ]:
%%time
#  Use MDS to reduce the MNIST dataset, show result graphically
reducer = MDS(n_components=2, n_jobs=-1)
X_reduced = reducer.fit_transform(X_subsampled_data)
display(X_reduced.shape)
display(X_reduced)
fig = px.scatter(x=X_reduced[:,0], y=X_reduced[:,1], color=y_subsampled_data, title="MDS")
fig.update_layout(coloraxis_colorbar=dict(title=TARGET), height=1000)
fig.update_yaxes(scaleanchor = "x", scaleratio = 1)
fig.show()

/usr/local/lib/python3.10/dist-packages/sklearn/manifold/_mds.py:299: FutureWarning:

The default value of `normalized_stress` will change to `'auto'` in version 1.4. To suppress this warning, manually set the value of `normalized_stress`.



(5000, 2)

array([[-16.22454348, -33.01680488],
       [  2.90100458, -17.72504168],
       [  7.33561929,   1.70551602],
       ...,
       [ -9.67370734,   3.62609246],
       [  7.13118427,   9.23251737],
       [  0.73195697, -16.44652296]])

CPU times: user 9.48 s, sys: 1.89 s, total: 11.4 s
Wall time: 11min 51s


**Comparison:**
 - t-SNE: Exhibits clear cluster separation, indicating effective dimensionality reduction and distinct groupings within the data.
 - LLE: Less effective than t-SNE because it looks like two broad arms extending from a denser cluster at the center, and there is data overlap.
 - MDS: Better than LLE but not as clear as t-SNE because it appears data overlap.